sudo: false
dist: trusty
language: node_js
node_js:
  - '4.2.6'

cache: apt

addons:
  firefox: "51.0"

install:
  - npm install -g web-ext

script:
  - scripts/deploy-firefox.sh --publish
  - scripts/deploy-chrome.sh --publish

deploy:
    provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: build/*
    skip_cleanup: true
    on:
      tags: true

